package com.upstox.queue;

import java.util.concurrent.PriorityBlockingQueue;
import java.util.concurrent.atomic.AtomicInteger;

import java.util.logging.Logger;

import com.upstox.model.OHLCData;

/**
*  A queue wrapper class to manage data generated by producer
*/
public class PacketsBlockingQueue{
    private static final Logger LOGGER = Logger.getLogger(PacketsBlockingQueue.class.getName());

    private static final AtomicInteger noOfPacketReceived = new AtomicInteger(0);
    private static final AtomicInteger noOfPacketsDelievered = new AtomicInteger(0);

    private final static int INITIALSIZE = 1_000;
    private final static PriorityBlockingQueue<OHLCData> packetsQueue = new  PriorityBlockingQueue<>(INITIALSIZE);

    public static OHLCData read(){
	try{
	    OHLCData ohlcData = packetsQueue.take();
            return ohlcData;
	}catch(InterruptedException ex){
	    LOGGER.info("Interrupted Exception " + ex.getMessage());
	}

	return null;
    }

    public static void write(final OHLCData ohlcData){ 
        packetsQueue.put(ohlcData);
    }
}
